use_frameworks!

platform :ios, '10.0'

target 'Rockstar_Example' do
  pod 'Rockstar', :path => '../', subspecs: [
    "RockstarCore", "RockstarApple"
  ]

  target 'Rockstar_Tests' do
    inherit! :search_paths
  end
end
